name: treeed
description: A Dart minimalistic state manager.
version: 0.1.0
repository: https://github.com/marat0n/treeed

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - state-manager
  - architecture-agnostic
  - treeed
  - tree-based-state
  - minimalistic
